# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180318_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'ordering': ['-count'], 'verbose_name': 'Product in Order', 'verbose_name_plural': 'Products in Order'},
        ),
    ]
